PALABRAS = {
    "camisa": ["camisa", "cima", "masa", "mica", "casi", "asma", "misa", "saca", "as", "caia","cami" ],
    "platos": ["platos", "plato", "alto", "palo", "sol", "sal", "las", "sola", "paso", "pasto", "post", "talo", "topa", "ola", "tal", "ato"],
    "amigos": ["amigos", "amigo", "goma", "sima", "gas", "oiga", "sigo", "gamo", "mago", "soga", "isla", "mis", "asi"],
    "tierra": ["tierra", "tira", "arte", "aire", "ira", "rie"],
    "puente": ["puente", "ente"],
    "soleado": ["soleado", "sola", "lado", "sal", "osado", "ola", "dos"],
    "lanzas": ["lanzas", "lanza", "sal", "alas"],
    "puerta": ["puerta", "pura", "ruta", "pera"],
    "cuadro": ["cuadro", "rudo", "duro", "arduo", "cura", "dar", "arco"],
    "cuerda": ["cuerda", "cura", "ruda", "cera", "acre"], 
    "famosa": ["famosa", "fama", "masa", "osa", "fosa"],
    "camion": ["camion", "cima", "mano", "mica", "mico"],
    "planta": ["planta", "plan", "pala", "tala", "nata", "alta", "palta", "lana"],
    "marino": ["marino", "mar", "amor", "mina", "ramo"],
    "brillo": ["brillo", "rio"],
    "sombra": ["sombra", "broma", "soba", "mora"],
    "escudo": ["escudo", "sueco", "codo", "eco", "duro", "rudo"],
    "torres": ["torres", "torre", "resto"],
    "cuchara": ["cuchara", "cura", "arca", "cara"],
    "sabana": ["sabana", "sana"],
    "torneo": ["torneo", "norte", "tenor", "tono", "reto", "oro", "ron", "terco", "reo"],
    "camino": ["camino", "camino", "manco", "mano", "cima", "camo", "mino", "naco", "mico", "cami"],
    "gorras": ["gorras", "gora", "rasgo", "saga", "gas", "rosa", "soga", "osar"],
    "bancos": ["bancos", "banco", "canso", "cosa", "bano", "nos", "con", "son", "cano", "coba", "beso"],
    "campos": ["campos", "campo", "copas", "paco", "sopa", "capo", "posa", "cosa", "paso", "como", "amos"],
    "cables": ["cables", "cable", "bale", "sale", "cal", "les", "ceba", "besa"],
    "sillas": ["sillas", "silla", "sali", "lisa", "isla", "las"],
    "casita": ["casita", "citas", "casa", "tasa", "tas", "cita", "sita"],
    "plazas": ["plazas", "plaza", "lapa", "pala", "alza", "sal", "las", "paz"],
    "tercio": ["tercio", "corte", "eco", "reto", "cero", "terco", "rocio", "rico"],
    "bronce": ["bronce", "cono", "cero", "cebo", "reo"],
    "aviones": ["aviones", "avion", "savia", "son", "aves", "nave", "via", "vino", "sano", "visa", "anis", "veo", "oia"],
    "colores": ["colores", "color", "sol", "loro", "roles", "celo", "creo", "roce", "leo"],
    "familia": ["familia", "mil", "fila", "mal", "lia", "fama", "llama"],
    "escuela": ["escuela", "celas", "saca", "sale", "sal", "las", "causa", "se", "acusa"],
    "botella": ["botella", "bote", "tela", "alto", "bello", "balle", "olla", "lote", "al", "leo"],
    "regalo": ["regalo", "ruego", "gala", "algo", "ola", "leo", "ore", "dar"],   
    "cartera": ["cartera", "rata", "arte", "cara", "cera", "rara", "teca", "rata"],
    "cabeza": ["cabeza", "cabe", "casa", "caza", "caza", "haz", "baza", "abeza"],
    "dinero": ["dinero", "orden", "don", "rio", "dire", "dino", "red", "reo"],
    "ventana": ["ventana", "veta", "nata", "ante", "tan", "vena", "ana", "neto"],
    "cancion": ["cancion", "cana", "no", "cien", "con"],
    "musica": ["musica", "suma", "casi", "misa", "sima", "usa", "asi", "mas"],
    "deporte": ["deporte", "red", "peor", "reto", "pedro", "ote", "reo"],
    "colegio": ["colegio", "cole", "ocio", "eco", "oigo", "lego", "gol"],
    "trabajo": ["trabajo", "tarja", "bota", "bajo", "jaba", "taja", "bar", "ajo"],
    "celular": ["celular", "cura", "real", "azul", "luce", "claro", "crea", "caer"],
    "computadora": ["computadora", "coto", "puta", "tropa", "rata", "data", "dar", "amor", "poda", "cura"],
    "bolsillo": ["bolsillo", "bolso", "silo", "solo", "sol", "lio"],
    "almuerzo": ["almuerzo", "azul", "mar", "muro", "zum", "mozo", "mal", "mora"],
    "desayuno": ["desayuno", "uso", "don", "dos", "seda", "sano", "no"],
    "chocolate": ["chocolate", "cola", "tela", "lote", "chal", "hola", "choza", "taco", "ocho"],
    "television": ["television", "lente", "leo", "veo", "no", "sol"],
    "pelicula": ["pelicula", "lupa", "pila", "pule", "pica", "lice", "piel", "cura"],
    "internet": ["internet", "tener", "tren", "ente", "tres"],
    "tienda": ["tienda", "den", "dia", "tan", "ten", "tia"],
    "hospital": ["hospital", "alto", "sopa", "piso", "osa", "pila", "sal", "sol", "pasto", "olas", "ola", "palo", "palos" ],
    "medico": ["medico", "miedo", "medio", "demo" ],
    "camara": ["camara", "cara", "arma", "arca", "mar", "cama","rama"],
    "viajes": ["viajes", "viaje", "si", "via", "vias", "visa"],
    "pasaje": ["pasaje", "pasa", "as","pesa"],
    "aeropuerto": ["aeropuerto", "puerto", "puerta", "aereo", "europeo", "porteo", "reporte", "tropa" ],
    "maleta": ["maleta", "metal", "tela", "mal", "mate"],
    "llaves": ["llaves", "velas", "valles", "vela", "valle"],
    "libros": ["libros", "bolsos", "sol", "rio", "libro", "bolso", "rol"],
    "cuentos": ["cuentos", "cuento", "tos", "unos", "eco", "seco", "uno"],
    "pintura": ["pintura", "ruta" , "pin" , "punta" , "pintar", "nutria","patin", "tina", "tira"]
}
